package hw01.digitalsignature;

import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class SHA {

	public SHA() {
		
	}
	
	public BigInteger performSHA(String input) 
    { 
  
        try { 
  
            // Static getInstance method is called with hashing SHA 
            MessageDigest md = MessageDigest.getInstance("SHA-256"); 
  
            // digest() method called 
            // to calculate message digest of an input 
            // and return array of byte 
            byte[] messageDigest = null;
			try {
				messageDigest = md.digest(input.getBytes("UTF-8"));
			} catch (UnsupportedEncodingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} 
  
            // Convert byte array into signum representation 
            BigInteger no = new BigInteger(1, messageDigest); 
            
            return no; 
        } 
  
        // For specifying wrong message digest algorithms 
        catch (NoSuchAlgorithmException e) { 
            System.out.println("Exception thrown"
                               + " for incorrect algorithm: " + e); 
  
            return null; 
        } 
    } 
  
    public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
    	SHA sha = new SHA();
    	
        System.out.println("HashCode Generated by SHA-256 for:"); 
  
        String s1 = "GeeksForGeeks"; 
        System.out.println("\n" + s1 + " : " + sha.performSHA(s1)); 
  
        String s2 = "hello world"; 
        System.out.println("\n" + s2 + " : " + sha.performSHA(s2)); 
    } 
	
	
	
}
